name: Flutter Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository'yi çek
        uses: actions/checkout@v3

      - name: Flutter kur
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Paketleri indir
        run: flutter pub get

      - name: APK üret
        run: flutter build apk --release

      - name: APK'yı kayıt et
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
