name: Debug Flutter Project

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show root folder
        run: |
          echo "===== ROOT DIRECTORY ====="
          ls -R .

      - name: Show second level
        run: |
          echo "===== SECOND LEVEL ====="
          ls -R */ || echo "No subfolders"